### ISSUE TITLE
Just need a little help...

### ISSUE THREAD

**Issue by Fasani** [bvaughn/redux-search#59]
I am having some difficulty with redux-search and I am not familiar with immutable, is it a requirement? I have spent some hours today trying to figure it out but I am at a dead end. I would really appreciate any feedback.

I have this.props.state.search returning what looks like a working search object, I get search text and a list of id that match the text in the title field. I implemented that part of the project like so:

```javascript
const rootReducer = combineReducers({
  foodsDB: foodsDB,
  search: searchReducer
});

const enhancer = compose(
  reduxSearch({
    resourceIndexes: {
      foodsDB: ['title']
    },
    resourceSelector: (resourceName, state) => {
      return state[resourceName];
    }
  })
)
```

Now the problem I have is with this code below which is attached under my App component. I do not get any errors and I do see several functions being returned on this.props.selectors

I just assume I am missing something or I have a final bit of code to add somewhere in my render method or reducers or somewhere else .... (Sorry I have no idea).

```javascript

const foodsDB = state => state['foodsDB']

const {
  text, // search text
  result // food ids
} = getSearchSelectors({
  resourceName: 'foodsDB',
  resourceSelector: (resourceName, state) => state[resourceName]
})

const selectors = createSelector(
  [result, foodsDB, text],
  (foodIDs, foodsDB, searchText) => ({
    foodIDs,
    foodsDB,
    searchText
  })
)

// Wrap State and DispatchEvents into the App with Redux
const mapStateToProps = (store) => ({
  store,
  selectors
});

const mapDispatchToProps =  ({
  toggleActive: toggleActive,
  searchFoodDB: createSearchAction('foodsDB')
});

const appWrappedWithRedux = connect(
  mapStateToProps,
  mapDispatchToProps
)(App);

export default appWrappedWithRedux;
```
Thanks in Advance!

**Comment by bvaughn** [comment]
Hey @Fasani,

> I am having some difficulty with redux-search and I am not familiar with immutable, is it a requirement?

No, ImmutableJS is not a requirement. The demo [here](https://bvaughn.github.io/redux-search/) (source [here](https://github.com/bvaughn/redux-search/tree/master/website)) shows examples of both an Immutable `Map` and a vanilla JavaScript `Object` as searchable sources. Take a look there and compare it to what you're doing in your app?

I don't think you've provided enough code for me to diagnose what's going on. This type of question is probably better directed to Stack Overflow anyway. Maybe give it a try on SO and ping me again here in a day or two if you haven't gotten an answer? 😄 

Going to close this for now as it's a question and not an issue that needs to be fixed with redux-search.

**Comment by Fasani** [comment]
Thank You for your time.
