### ISSUE TITLE
Indexes

### ISSUE THREAD

**Issue by dropring** [bvaughn/redux-search#61]
Hello. How can I get indexes of filtered data instead of ids?

**Comment by bvaughn** [comment]
I don't understand. Could you give an example?


On Mar 5, 2017 6:12 PM, "dropring" <notifications@github.com> wrote:

Hello. How can I get indexes of filtered data instead of ids?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bvaughn/redux-search/issues/61>, or mute the thread
