### ISSUE TITLE
best practice for further filtering and sorting

### ISSUE THREAD

**Issue by slavab89** [bvaughn/redux-search#64]
I've wanted to get your opinion on how to best use this library for searching, filtering and ordering the data.
Say i have a collection of books that has some id, name, author attributes.

In my UI i have a search box that will utilize redux-search library - only by book name for example.

I'll also have a select box to further filter the books collection by auther - meaning that if i select some author in the select box, the result set will be filtered and reduced once more (only to show the books of that author) - can be done using `filterFunction` in the `getSearchSelectors `.

Finally i'll be able to somehow choose a sorting for the books, and that sorting will be done in the same  `filterFunction`.

Is this a correct approach? Or is there some other recommendation for this?
I'm asking this mainly because when searching data, i dont really know the order that the id's are going to come back - is it correct? So they do not define the order of my actual data.

**Comment by bvaughn** [comment]
> I'll also have a select box to further filter the books collection by auther - meaning that if i select some author in the select box, the result set will be filtered and reduced once more (only to show the books of that author) - can be done using filterFunction in the getSearchSelectors.

This would require a separate search index, based on the first. You could maybe try to setting up a second redux-search that pointed at the filtered output of the first one. I'm not sure how well this would work because I haven't tried it before. Might be kind of slow. If I were you, I would maybe consider actually using the underlying search library ([js-worker-search](https://github.com/bvaughn/js-worker-search)) direction for this.

> Finally i'll be able to somehow choose a sorting for the books, and that sorting will be done in the same `filterFunction`.

Sorting should be done by a selector, post-filter.

**Comment by slavab89** [comment]
Many thanks!
i'll look into that. The additional filtering does seems like an additional search by nature, just that they both affect the same data source.
Currently, because i have a small dataset i'm doing the additional filter using the `filterFunction` as part of the selector and it does work. For performance i know that its not ideal and once i'll have a bigger data set it will be even more troublesome.

**Comment by bvaughn** [comment]
Yeah.

Unfortunately js-worker-search (and so redux-search too) weren't architected with the idea of supporting multiple drill-down searches. So the only way to do that would be to re-index for the follow-up search. I'd suggest _not_ using redux-search for that because the re-index would happen every time you searched the book names and I _think_ you probably don't want that. You probably only want it to happen if and when a user clicks the second checkbox.
